//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasketballCompetition
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerHistory
    {
        public int Id { get; set; }
        public string ClubName { get; set; }
        public string Post { get; set; }
        public int GameNumber { get; set; }
        public string Role { get; set; }
        public double Height { get; set; }
        public double Weight { get; set; }
        public System.DateTime Date { get; set; }
        public int IdPlayer { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
