//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasketballCompetition
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingHall
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public int Capacity { get; set; }
        public string Phone { get; set; }
        public int IdCategory { get; set; }
        public int IdClub { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Club Club { get; set; }
    }
}
